import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Cucina Colore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout imageSrc="/img/stock-wine.jpg" imageAlt="Wall of bottled wine" imageClassName="home__image">
        <section className="home__reservations" >
          <h2>MAKE A RESERVATION</h2>
        </section>
      </Layout>
    </div>
  )
}

export default Home
