import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Cucina Colore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout imageSrc="/img/stock-chef-dough.jpg" imageAlt="Chef making pizza dough" imageClassName="home__image">
        <h3>HELLO</h3>
      </Layout>
    </div>
  )
}

export default Home
